// `.env.ts` is generated by the `npm run env` command
// `npm run env` exposes environment variables as JSON for any usage you might
// want, like displaying the version or getting extra config from your CI bot, etc.
// This is useful for granularity you might need beyond just the environment.
// Note that as usual, any environment variables you expose through it will end up in your
// bundle, and you should not use it for any sensitive information like passwords or keys.
import { env } from './.env';

export const environment = {
  production: true,
  hmr: false,
  version: env.npm_package_version,
  awsUrl: 'https://zggxtkhqb6.execute-api.us-east-1.amazonaws.com/dev',
  topicArn: "arn:aws:sns:us-east-1:696855912264:example-topic",
  defaultLanguage: 'en-US',
  supportedLanguages: ['en-US'],
};
